# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6047761819ed7e04d5d3b330f5cda1e392ac5fa9b524fb6084931dbe984394085f76621ffc963d8baff7f31c8518a35ae6a9405d70d7044b16ba68963a4ed58f

test:
  secret_key_base: 629dc8069610b6dcab08d9d29b23c5e6dacb463a41850319046c275f5b478b4b2d3aac9ef55ea746e2dc66b77968e030f704bd202503326fd6fd64f19723270d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
